### ISSUE TITLE
Solflare Wallet Disconnect Probelm

### ISSUE THREAD

**Issue by NurettinSelim** [merigo-labs/solana-wallet-provider#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**
When I want to disconnect the Solflare wallet, It sends me to a chrome browser page with this url
https://solflare.com/mobilewalletadapterv1/associate/local?port=64860&association=BMXJPQ...

**Mobile device (please complete the following information):**
 - Name: Android Emulator
 - OS:  API 31

**Comment by merigo-labs** [comment]
Hi @NurettinSelim,

Which version of solana_wallet_provider are running? Can you try running the latest version `0.0.5+2` (if you're not already).

Thanks

**Comment by NurettinSelim** [comment]
It works but needs a little adjustment in "AndroidManifest.xml" to open "solana-wallet" URI.
I needed to add these lines out of the "Application" tag.
```
<queries>
    <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="solana-wallet" />
    </intent>
</queries>

**Comment by merigo-labs** [comment]
Brilliant! I've updated the package (version `0.0.6`) to include this. Thank you for bringing the issue to my attention and let me know if you need anything else.
